version: '3.8'

services:
  philly-wings:
    build: .
    container_name: philly-wings-dev
    ports:
      # Vite dev server
      - "5173:5173"
      # Firebase Emulator UI
      - "4000:4000"
      # Firebase Auth
      - "9099:9099"
      # Firestore
      - "8080:8080"
      # Storage
      - "9199:9199"
      # Hosting
      - "5000:5000"
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      # Persist Firebase emulator data
      - firebase_data:/app/emulator-data
    environment:
      - NODE_ENV=development
      - FIREBASE_PROJECT=philly-wings
    networks:
      - philly-network

  # Optional: Nginx for production-like testing
  nginx:
    image: nginx:alpine
    container_name: philly-wings-nginx
    ports:
      - "8888:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - philly-wings
    networks:
      - philly-network
    profiles:
      - production

networks:
  philly-network:
    driver: bridge

volumes:
  firebase_data: